Use Fluo and Accumulo version installed for shaded jar
astralway/stresso pull request #46
Opened 2016-09-23 18:57 UTC by keith-turner

2016-09-23 20:17 UTC, mikewalch commented on bin/run-test.sh
> +mvn dependency:copy-dependencies  -DincludeArtifactIds=fluo-recipes-core -DoutputDirectory=$FLUO_APP_LIB
interesting.. does it copy the version set in your pom.xm?

2016-09-23 20:24 UTC, mikewalch commented on conf/env.sh.example
> +ACCUMULO_VERSION=$(accumulo version)
Should mention in README.md that accumulo command should be on PATH. It already mentions that yarn and hadoop should be there.

2016-09-23 20:26 UTC, mikewalch commented on conf/env.sh.example
> +# To run map reduce jobs a shaded jar is built, the following properties
Could be `To run MapReduce jobs, a shaded jar is built. The following`

2016-09-23 20:27 UTC, mikewalch requested changes

2016-09-23 20:35 UTC, mikewalch commented
I used `run-test.sh` to run stresso locally using Uno.  Everything worked for me.

2016-09-23 20:50 UTC, keith-turner commented on bin/run-test.sh
> +mvn dependency:copy-dependencies  -DincludeArtifactIds=fluo-recipes-core -DoutputDirectory=$FLUO_APP_LIB
Yeah it uses the version in the pom.

2016-09-29 18:26 UTC, mikewalch approved these changes
+1

2016-09-29 18:29 UTC, merged